export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_FAILURE = 'GOOGLE_LOGIN_FAILURE';
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS ';
export const FACEBOOK_LOGIN_FAILURE = 'FACEBOOK_LOGIN_FAILURE';
export const LOCAL_LOGIN_SUCCESS = 'LOCAL_LOGIN_SUCCESS';
export const LOCAL_LOGIN_FAILURE = 'LOCAL_LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';